definitions:
  handler.signInInput:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  models.TodoItem:
    properties:
      description:
        type: string
      done:
        type: boolean
      id:
        type: integer
      title:
        type: string
    required:
    - title
    type: object
  models.User:
    properties:
      name:
        type: string
      password:
        type: string
      username:
        type: string
    required:
    - name
    - password
    - username
    type: object
info:
  contact: {}
paths:
  /api/items/:id:
    get:
      consumes:
      - application/json
      description: Get items Id for current user
      parameters:
      - description: Bearer Auth, pls add bearer before
        in: header
        name: Authorization
        required: true
        type: string
      - description: item info
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/models.TodoItem'
      - description: id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "201":
          description: id
          schema:
            type: string
      summary: Get item by Id
      tags:
      - items
  /api/lists/:id/items:
    post:
      consumes:
      - application/json
      description: Get all items from the list of current user
      parameters:
      - description: Bearer Auth, pls add bearer before
        in: header
        name: Authorization
        required: true
        type: string
      - description: item info
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/models.TodoItem'
      - description: id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "201":
          description: id
          schema:
            type: string
      summary: Get all items
      tags:
      - items
  /api/lists/{id}/items:
    post:
      consumes:
      - application/json
      description: Creating new item inside the list for current user
      parameters:
      - description: Bearer Auth, pls add bearer before
        in: header
        name: Authorization
        required: true
        type: string
      - description: item info
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/models.TodoItem'
      - description: id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "201":
          description: id
          schema:
            type: string
      summary: Create Item
      tags:
      - items
  /auth/sign-in:
    post:
      consumes:
      - application/json
      description: logging in the user
      parameters:
      - description: username password
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/handler.signInInput'
      produces:
      - application/json
      responses:
        "200":
          description: someToken
          schema:
            type: string
      summary: sign in
      tags:
      - auth
  /auth/sign-up:
    post:
      consumes:
      - application/json
      description: register a new user
      parameters:
      - description: account info
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
      summary: sign up
      tags:
      - auth
swagger: "2.0"
