version: '3.8'

services:
  web:
    build: .
    env_file:
      - ./app.env
    image: todo
    depends_on: 
      - db
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: StrongPw01
      DB_NAME: postgres
    links:
      - db
    volumes:
      - './:/todo'
  db: 
    image : postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports: 
      - '5432:5432'
    volumes:
      # - db:/var/lib/postgresql/data
      - ./src/migrations/up.sql:/docker-entrypoint-initdb.d/up.sql
volumes: 
  db: 
    driver: local